services:
  - type: web
    name: coop-backend
    env: python
    rootDir: .
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r backend/requirements.txt && \
      python backend/manage.py collectstatic --noinput
    startCommand: |
      python backend/manage.py migrate && \
      gunicorn core.wsgi:application --chdir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_USER
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
